name: CI/CD Workflow with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-app-image .

      - name: Run tests inside Docker container
        run: |
          docker run my-app-image npm test

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker tag my-app-image ${{ secrets.DOCKER_USERNAME }}/my-app-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app-image:latest
