name: CI/CD Workflow with Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t m3se/githubactions:latest .

      # Add test execution step
      - name: Run Tests Inside Docker Container
        run: docker run m3se/githubactions:latest npm test  # Adjust for your test command

      - name: Push Docker Image to Docker Hub
        run: docker push m3se/githubactions:latest

      - name: Run Docker Container
        run: docker run -d -p 8080:8080 m3se/githubactions:latest
